DROP TABLE IF EXISTS ghouses;

CREATE TABLE ghouses(
  id SERIAL PRIMARY KEY ,
  gh_id SMALLINT NOT NULL,
  temperature REAL NOT NULL,
  humidity REAL NOT NULL,
  tlevel SMALLINT NOT NULL,
  idate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
